Repository Besufqad-Mesfin/school-portal-server, pull requests merged in 2025-01, with the labels that each got.

#57 Implement department management controllers for create, read, update, and…
  department service/controllers/department.js
Labels: enhancement

#60 Add Payment Creation Functionality (#75)
  payment service/.gitignore
  payment service/Middleware/authMiddleware.js
  payment service/README.md
  payment service/config/db.js
  payment service/controllers/paymentControllers.js
  payment service/index.js
  payment service/models/paymentModels.js
  payment service/package-lock.json
  payment service/package.json
  payment service/routes/api.js
  payment service/routes/paymentRoutes.js
  payment-service/.gitignore
  payment-service/Middleware/authMiddleware.js
  payment-service/controllers/paymentController.js
  payment-service/index.js
  payment-service/models/Payment.js
  payment-service/package-lock.json
  payment-service/package.json
  payment-service/routes/paymentRoutes.js
Labels: bug, enhancement

#99 Add Sequelize configuration for database connection
  grading and assessment service/config/db.js
Labels: bug, documentation, enhancement

#106 create a grade model file and implement the grade table
  grading and assessment service/models/Report.js
  grading and assessment service/models/gradeModel.js
Labels: bug, enhancement

#108 Create a grade controller file and implement the function needed by grade router
  grading and assessment service/controllers/gradeController.js
  grading and assessment service/controllers/report.js
Labels: bug, enhancement

#110 Update a common endpoints for assessment in api.js
  grading and assessment service/routes/api.js
Labels: bug, enhancement

#112 Implement the assessment router code
  grading and assessment service/controllers/gradeController.js
  grading and assessment service/routes/api.js
  grading and assessment service/routes/assessmentRouter.js
Labels: bug, enhancement
