Repository Besufqad-Mesfin/school-portal-server, pull requests merged in 2025-02, with the labels that each got.

#114 Create a assessment model and implement the assessment table
  grading and assessment service/models/assessmentModel.js
Labels: bug, enhancement

#116 Create a assessment controller file and implement the function needed by assessment router
  grading and assessment service/controllers/assessmentController.js
Labels: bug, enhancement

#72 Implement Reporting Functionality for Library Management
  library service/.gitignore
  library service/Middleware/authMiddleware.js
  library service/README.md
  library service/config/db.js
  library service/controllers/bookControllers.js
  library service/index.js
  library service/models/BookTransaction.js
  library service/models/bookModels.js
  library service/routes/api.js
  library service/routes/bookRoutes.js
  library-service/Middleware/authMiddleware.js
  library-service/config/db.js
  library-service/controllers/bookController.js
  library-service/index.js
  library-service/models/Book.js
  library-service/package-lock.json
  library-service/package.json
  library-service/routes/api.js
  user manegment service/package-lock.json
  user manegment service/package.json
Labels: documentation, enhancement

#123 Add notification routes for student grades, announcements, teacher as…
  notification service/routes/notificationRoutes.js
Labels: enhancement

#128 Notification routes
  notification service/routes/notificationRoutes.js
Labels: enhancement

#130 Implement notification controller code
  notification service/controllers/notificationController.js
Labels: bug, enhancement
